TEXTS = {
    "Spn": {
        "resolution": "Resolución",
        "window_mode": "Modo Ventana",
        "audio": "Sonido",
        "music": "Música",
        "play": "JUGAR",
        "register": "Registrarse",
        "language": "Idioma",
        "volume": "Volumen",
        "version": "Versión",
        "launching": "Lanzando...",
        "verify_update_btn": "Verificar y Actualizar Cliente ⬇️⏬",
        "verifying": "Verificando...",
        "downloading": "Descargando",
        "connecting_server": "Conectando con el servidor...",
        "client_updated": "¡Cliente actualizado! Ya podés jugar.",
        "status_ready": "Estado: Listo",
        "connection_error": "Error de conexión con el servidor",
        "error": "Error",
        "save": "Guardar",
        "options_title": "Opciones"
    },
    "Eng": {
        "resolution": "Resolution",
        "window_mode": "Window Mode",
        "audio": "Sound",
        "music": "Music",
        "play": "PLAY",
        "register": "Register Now",
        "language": "Language",
        "volume": "Volume",
        "version": "Version",
        "launching": "Launching...",
        "verify_update_btn": "Verify and Update Client ⬇️⏬",
        "verifying": "Verifying...",
        "downloading": "Downloading",
        "connecting_server": "Connecting to server...",
        "client_updated": "Client updated! Ready to play.",
        "status_ready": "Status: Ready",
        "connection_error": "Server connection error",
        "error": "Error",
        "save": "Save",
        "options_title": "Options"
    },
    "Por": {
        "volume": "Volume",
        "audio": "Som",
        "music": "Música",
        "resolution": "Resolução",
        "window_mode": "Modo Janela",
        "play": "JOGAR",
        "register": "Registrar-se",
        "language": "Idioma",
        "version": "Versão",
        "launching": "Iniciando...",
        "verify_update_btn": "Verificar e Atualizar Cliente ⬇️⏬",
        "verifying": "Verificando...",
        "downloading": "Baixando",
        "connecting_server": "Conectando ao servidor...",
        "client_updated": "Cliente atualizado! Pronto para jogar.",
        "status_ready": "Status: Pronto",
        "connection_error": "Erro de conexão com o servidor",
        "error": "Erro",
        "save": "Salvar",
        "options_title": "Opções"
    }
}